---
- name: Restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: True

- name: Restart prometheus-oauth2
  systemd:
    name: prometheus-oauth2
    state: restarted
    daemon_reload: yes

...
